mode = "light"

accent = "#007acc"
selection = "#d0cfc9"
muted = "#77756e"

background = "#e5e4df"
dark_background = "#deddd8"
darker_background = "#cecdc7"
lighter_background = "#f7f7f4"

foreground = "#26251e"
dark_foreground = "#77756e"
light_foreground = "#57564f"
bright_foreground = "#000000"

red = "#aa3731"
yellow = "#cb9000"
orange = "#d28a00"
green = "#448c37"
cyan = "#0083b2"
blue = "#325cc0"
magenta = "#7a3e9d"
brown = "#7a5a3a"

bright_red = "#f05050"
bright_yellow = "#ffbc5d"
bright_green = "#60cb00"
bright_cyan = "#00aacb"
bright_blue = "#007acc"
bright_magenta = "#e64ce6"
