tap "can1357/tap", trusted: { formula: "omp" }

brew "btop"
brew "fish"
brew "can1357/tap/omp"
brew "rclone"
brew "trash"
brew "usage"
brew "zsh-autosuggestions"

cask "1password"
cask "1password-cli"
cask "anki"
cask "arq"
cask "codex-app"
cask "cursor"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "helium-browser"
cask "obsidian"
cask "openscad@snapshot"
cask "raycast"
cask "slack"
cask "spotify"
cask "tailscale-app"
cask "zed"
