hostname = `hostname`.strip

brew "git"
brew "mise"
brew "trash"
brew "fish"

cask "google-chrome"
cask "1password"
cask "hammerspoon"
cask "raycast"
cask "spotify"
cask "zoom"
cask "cleanshot"
cask "slack"
cask "ghostty"
cask "discord"
cask "orbstack"
cask "nikitabobko/tap/aerospace"
cask "karabiner-elements"
cask "macwhisper"
cask "antinote"
cask "bartender"
cask "istat-menus"
cask "tailscale" if hostname == "turbochardo"
