brew "trash"
brew "qemu"
brew "neurosnap/tap/zmx"

cask "1password"
cask "1password-cli"
cask "ghostty"
cask "google-chrome"
cask "obsidian"
cask "raycast"
cask "slack"
cask "spotify"
cask "tailscale-app"
cask "anki"
cask "zed"
cask "font-jetbrains-mono-nerd-font"
