[tools]
atuin = "latest"
direnv = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
"github:neurosnap/zmx" = "latest"
jj = "latest"
jjui = "latest"
jq = "latest"
neovim = "latest"
node = "24"
pi = "latest"
ripgrep = "latest"
tmux = "latest"
tree-sitter = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
