# Window/Tab Management
enabled_layouts splits
map cmd+w close_window
map cmd+t new_tab_with_cwd
map cmd+enter new_window_with_cwd
map cmd+d launch --type window --cwd current --location vsplit
map cmd+shift+d launch --type window --cwd current --location hsplit
map cmd+[ previous_window
map cmd+] next_window

# Scrollback config
map ctrl+f>[ show_scrollback

# vim-test-output
map ctrl+f>t>n launch --type os-window --title "vim-test-output" --cwd current
map ctrl+f>t>j detach_window as
map ctrl+f>t>d detach_window new-os-window

# Misc keybinds
map ctrl+f>r load_config_file
map ctrl+f>s kitten hints --type regex --regex "aws sso login.*" --program "launch --type=overlay fish -c"
map super+z toggle_layout stack

# tab title
tab_title_template "{sup.layout_name[:1].upper()}{title}{sup.num_windows}"

# Remote control
allow_remote_control yes
listen_on unix:/tmp/kitty

# Terminal settings
scrollback_lines 100000
enable_audio_bell no
macos_option_as_alt yes

# Shell integration
shell_integration enabled
shell /opt/homebrew/bin/fish

# Font settings
font_size 15
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

# Colors (Gruvbox Dark Hard)
background #1d2021
foreground #ebdbb2
selection_background #ebdbb2
selection_foreground #1d2021
cursor #ebdbb2
cursor_text_color #1d2021

# Black
color0 #282828
color8 #928374

# Red
color1 #cc241d
color9 #fb4934

# Green
color2  #98971a
color10 #b8bb26

# Yellow
color3  #d79921
color11 #fabd2f

# Blue
color4  #458588
color12 #83a598

# Magenta
color5  #b16286
color13 #d3869b

# Cyan
color6  #689d6a
color14 #8ec07c

# White
color7  #a89984
color15 #ebdbb2

# Tab bar
active_tab_foreground   #ebdbb2
active_tab_background   #504945
inactive_tab_foreground #a89984
inactive_tab_background #3c3836


# Vim + Kitty Pane Integration
map ctrl+w>j neighboring_window down
map ctrl+w>k neighboring_window up
map ctrl+w>h neighboring_window left
map ctrl+w>l neighboring_window right

# Unset the mapping to pass the keys to neovim
map --when-focus-on var:IS_NVIM ctrl+w>j
map --when-focus-on var:IS_NVIM ctrl+w>k
map --when-focus-on var:IS_NVIM ctrl+w>h
map --when-focus-on var:IS_NVIM ctrl+w>l

#the 3 here is the resize amount, adjust as needed
map alt+shift+down kitten relative_resize down  3
map alt+shift+up kitten relative_resize up    3
map alt+shift+left kitten relative_resize left  3
map alt+shift+right kitten relative_resize right 3

map --when-focus-on var:IS_NVIM alt+shift+left
map --when-focus-on var:IS_NVIM alt+shift+right
map --when-focus-on var:IS_NVIM alt+shift+up
map --when-focus-on var:IS_NVIM alt+shift+down
