# See https://sw.kovidgoyal.net/kitty/conf.html

allow_remote_control yes
input_delay 1
repaint_delay 1
listen_on unix:/tmp/mykitty
macos_option_as_alt yes
shell_integration enabled
startup_session ~/.config/kitty/startup-session.conf
map f5 load_config_file

enabled_layouts tall, tall:bias=70

# BEGIN_KITTY_FONTS
font_family      family="BlexMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto font_size        16 # END_KITTY_FONTS

# BEGIN_KITTY_COLORS
background #1d2021
foreground #d5c4a1
selection_background #d5c4a1
selection_foreground #1d2021
url_color #bdae93
cursor #d5c4a1
active_border_color #665c54
inactive_border_color #3c3836
active_tab_background #1d2021
active_tab_foreground #d5c4a1
inactive_tab_background #3c3836
inactive_tab_foreground #bdae93
tab_bar_background #3c3836

# normal
color0 #1d2021
color1 #fb4934
color2 #b8bb26
color3 #fabd2f
color4 #83a598
color5 #d3869b
color6 #8ec07c
color7 #d5c4a1

# bright
color8 #665c54
color9 #fe8019
color10 #3c3836
color11 #504945
color12 #bdae93
color13 #ebdbb2
color14 #d65d0e
color15 #fbf1c7
# END_KITTY_COLORS

map cmd+e kitten hints
map cmd+a kitten hints --program="launch --type=background zsh -c" --type=regex --regex='aws sso login.*'

map cmd+equal change_font_size all +2.0
map cmd+minus change_font_size all -2.0

map cmd+enter launch --cwd=current --type=window --title=current
map cmd+t launch --type=tab --cwd=current
map cmd+w close_window
map cmd+[ next_window
map cmd+] previous_window

scrollback_pager nvim -c "set signcolumn=no showtabline=0" -c "silent write! /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - "

# Map cmd+up and cmd+down to send the F3 and F4 keys to the terminal (which I don't use)
# lazygit will use these to push/pull
map cmd+down send_text all \x1bOR
map cmd+up send_text all \x1bOS
