# Window/Tab Management
enabled_layouts tall:bias=0.7
map cmd+w close_window
map cmd+t new_tab_with_cwd
map cmd+enter new_window_with_cwd
map cmd+d new_window_with_cwd
map cmd+[ previous_window
map cmd+] next_window

map ctrl+f>[ show_scrollback

# Remote control
allow_remote_control yes
listen_on unix:/tmp/kitty

# Shell integration
shell_integration enabled
shell /opt/homebrew/bin/fish

# Terminal settings
scrollback_lines 100000
enable_audio_bell no
macos_option_as_alt yes

# Font settings
font_size 15
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

# Colors (Gruvbox Dark Hard)
background #1d2021
foreground #ebdbb2
selection_background #ebdbb2
selection_foreground #1d2021
cursor #ebdbb2
cursor_text_color #1d2021

# Black
color0 #282828
color8 #928374

# Red
color1 #cc241d
color9 #fb4934

# Green
color2  #98971a
color10 #b8bb26

# Yellow
color3  #d79921
color11 #fabd2f

# Blue
color4  #458588
color12 #83a598

# Magenta
color5  #b16286
color13 #d3869b

# Cyan
color6  #689d6a
color14 #8ec07c

# White
color7  #a89984
color15 #ebdbb2

# Tab bar
active_tab_foreground   #ebdbb2
active_tab_background   #504945
inactive_tab_foreground #a89984
inactive_tab_background #3c3836
