# See https://sw.kovidgoyal.net/kitty/conf.html

allow_remote_control yes
input_delay 1
repaint_delay 1
listen_on unix:/tmp/mykitty
macos_option_as_alt yes
enabled_layouts tall:bias=70,fat:bias=70,stack

tab_title_template "{bell_symbol}{activity_symbol}{'  ' if layout_name == 'stack' and num_windows > 1 else ''}{fmt.fg.tab}{sup.index}{title}"

# --------------------------------------------------------
# Font
# --------------------------------------------------------
font_family BlexMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14

# --------------------------------------------------------
# Colors
# --------------------------------------------------------
# default dark
background #181818
foreground #d8d8d8
selection_background #d8d8d8
selection_foreground #181818
url_color #b8b8b8
cursor #d8d8d8
active_border_color #585858
inactive_border_color #282828
active_tab_background #181818
active_tab_foreground #d8d8d8
inactive_tab_background #282828
inactive_tab_foreground #b8b8b8
tab_bar_background #282828

# normal
color0 #181818
color1 #ab4642
color2 #a1b56c
color3 #f7ca88
color4 #7cafc2
color5 #ba8baf
color6 #86c1b9
color7 #d8d8d8

# bright
color8 #585858
color9 #ab4642
color10 #a1b56c
color11 #f7ca88
color12 #7cafc2
color13 #ba8baf
color14 #86c1b9
color15 #f8f8f8

# extended base16 colors
color16 #dc9656
color17 #a16946
color18 #282828
color19 #383838
color20 #b8b8b8
color21 #e8e8e8

# --------------------------------------------------------
# Window/tab management
# --------------------------------------------------------
map cmd+w close_window
map cmd+e kitten hints
map cmd+equal change_font_size all +2.0
map cmd+minus change_font_size all -2.0

map ctrl+shift+enter launch --cwd=current --type=window
map cmd+tab launch --cwd=current --type=tab
map f5 load_config_file

map cmd+[ next_window
map cmd+] previous_window
map cmd+enter kitten toggle_terminal.py
