cd /Users/shardul/src/github.com/dbnlAI/dbnl-internal
launch --title="lazygit (dbnl-internal)" zsh -lc 'lazygit'
new_tab
cd /Users/shardul/src/github.com/dbnlAI/dbnl-internal
launch --title="shell (dbnl-internal)" zsh
new_tab
cd /Users/shardul/dotfiles
launch --title="lazygit (dotfiles)" zsh -lc 'lazygit'
new_tab
cd /Users/shardul/dotfiles
launch --title="shell (dotfiles)" zsh
