####
# Basic Settings
####

set -s escape-time 0 # Faster key repetition

unbind C-b
unbind C-a
unbind C-[
if-shell -b '[ $(uname) = "Darwin" ]' "set -g prefix C-f"
if-shell -b '[ $(uname) = "Linux" ]' "set -g prefix C-g"
# set -g prefix2 C-a

set -g base-index 1
setw -g pane-base-index 1
set -g history-limit 100000

# set -g default-command "if command -v reattach-to-user-namespace > /dev/null 2>&1; then reattach-to-user-namespace -l $SHELL; else $SHELL; fi"

setw -g mode-keys vi
unbind -T copy-mode-vi Space
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind H resize-pane -L 2
bind J resize-pane -D 2
bind K resize-pane -U 2
bind L resize-pane -R 2

setw -g mouse on
bind R source-file ~/.tmux.conf \; display "Configuration reloaded!"

bind Tab last-window

unbind q
bind q kill-pane

bind-key a select-pane -t -1

unbind-key x
bind x split-window -v -c '#{pane_current_path}'
bind v split-window -h -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'

####
# 256-color Support
####
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*col*:Tc"

####
# Status line
####
set -g status-interval 5
set -g status-bg colour234       # Gruvbox Hard background
set -g status-fg colour223       # Gruvbox foreground
set -g status-left ''
set -g status-right ''
# Show Mullvad city in orange, Git branch in green
set -g status-right "#[fg=colour166]#(curl -s https://am.i.mullvad.net/json | jq -r '.city') #[fg=colour142]#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD)"
set -g status-right-length 60

####
# Panes/Borders
####
# Active pane border in a slightly lighter gray, normal border in a dark gray
set -g pane-border-style fg=colour239
set -g pane-active-border-style bg=colour234,fg=colour241

####
# Window Title/Status
####
# Normal windows
set -g window-status-format "#[fg=colour244]#I:#T"
# Current window (macOS default)
set -g window-status-current-format "#[fg=colour223]#I:#T"

####
# Extra Options
####
set-window-option -g xterm-keys on
set-option -g focus-events on

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Move the current window to the left with ,
bind-key , swap-window -t -1\; select-window -t -1

# Move the current window to the right with .
bind-key . swap-window -t +1\; select-window -t +1

# Press prefix + u to open a popup with fzf for URLs
bind-key u popup \
  -E "tmux capture-pane -p | grep -Eo '(http|https)://[^ ]+' | fzf | xargs open"

set-option -g set-titles on
set-option -g set-titles-string '#T'

set-option -g renumber-windows on

bind-key -T copy-mode-vi Escape send-keys -X cancel
