customCommands:
  - key: "<c-g>"
    context: "commits"
    command: "gh browse {{.SelectedLocalCommit.Hash}}"
  - key: "<c-g>"
    context: localBranches
    command: "gh pr view {{.SelectedLocalBranch.Name}} --web"
  - key: "<c-g>"
    context: remoteBranches
    command: "gh pr view {{.SelectedRemoteBranch.Name}} --web"
  - key: "c"
    context: "commits"
    command: "git show HEAD | pbcopy"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers
  branchPrefix: "shardul/"
  commitPrefix:
    pattern: "^shardul/(\\w+-\\d+).*"
    replace: "[$1] "
gui:
  nerdFontsVersion: "3"
os:
  editPreset: "zed"
