# Dell XPS 13 DX13260 (sharchy): hardware, system, desktop, and user config.
{ config, hermes, lib, modulesPath, pkgs, ... }:

let
  authQml = ../config/quickshell-auth.qml;
  greeterShell = ../config/quickshell-greeter.qml;
  greeterConfig = pkgs.runCommand "sharchy-greeter-config" { } ''
    mkdir -p "$out"
    cp ${greeterShell} "$out/shell.qml"
    cp ${authQml} "$out/AlabasterAuth.qml"
  '';
  greeterSession = pkgs.writeShellScript "sharchy-greeter-session" ''
    export QT_QPA_PLATFORM=wayland
    export QT_SCALE_FACTOR=2
    export XKB_DEFAULT_OPTIONS=ctrl:nocaps
    export XCURSOR_THEME=macOS
    export XCURSOR_SIZE=24
    export XCURSOR_PATH=${pkgs.apple-cursor}/share/icons
    exec ${pkgs.dbus}/bin/dbus-run-session -- \
      ${pkgs.cage}/bin/cage -s -d -- \
      ${pkgs.quickshell}/bin/quickshell -p ${greeterConfig}
  '';
  cs35l56SpeakerFirmware = pkgs.runCommand "cs35l56-10280e53-spkid0-firmware" { } ''
    mkdir -p "$out/lib/firmware/cirrus"
    for suffix in .wmfw -ampl.bin -ampr.bin; do
      cp -L \
        "${pkgs.linux-firmware}/lib/firmware/cirrus/cs35l56-b2-dsp1-misc-10280e53-spkid1$suffix" \
        "$out/lib/firmware/cirrus/cs35l56-b2-dsp1-misc-10280e53-spkid0$suffix"
    done
  '';
in
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  networking.hostName = "sharchy";
  time.timeZone = "America/Montreal";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nixpkgs = {
    hostPlatform = lib.mkDefault "x86_64-linux";
    config.allowUnfree = true;
  };

  boot.initrd.systemd.enable = true;
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.initrd.luks.devices.cryptroot = {
    device = "/dev/disk/by-uuid/95ed11ca-d3f6-4f43-8969-50355533d068";
    allowDiscards = true;
    bypassWorkqueues = true;
    crypttabExtraOpts = [ "tpm2-device=auto" ];
  };
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=@" "compress=zstd:3" "noatime" ];
  };
  fileSystems."/home" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd:3" "noatime" ];
  };
  fileSystems."/nix" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress=zstd:3" "noatime" ];
  };
  fileSystems."/var/log" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=@log" "compress=zstd:3" "noatime" ];
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/EFI";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };
  swapDevices = [ ];

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.consoleLogLevel = 0;
  # Avoid choppy frame delivery from Panel Replay on the DX13260 display while
  # retaining lower-power PSR1 self-refresh.
  boot.kernelParams = [
    "xe.enable_psr=1"
    "xe.enable_psr2_sel_fetch=0"
    "xe.enable_panel_replay=0"
  ];
  # The XPS 13 DX13260 routes its CS35L56 woofer amps through a CS42L43
  # sidecar bridge. Force that bridge until the kernel recognizes SSID 1028:0e53.
  boot.extraModprobeConfig = "options snd_soc_sof_sdw quirk=65536";
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  hardware.enableRedistributableFirmware = true;
  # BIOS samples the speaker-ID GPIO too early and reports 0 during boot, but
  # the physical strap reads a stable 1 with every bias mode after boot. Alias
  # the matching Dell ID-1 tuning so the CS35L56 amplifiers can initialize.
  hardware.firmware = [ cs35l56SpeakerFirmware ];
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [ intel-media-driver vpl-gpu-rt ];
  };

  users.users.shardul = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" "input" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJyBr8fJpesCNZcxU+hDSBSUy34p8Z7VRRSctN2DYHqF shardul@gadget"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM29WLh4OM0d00gw6WyuWtwO2ZXvix3y0jwLdb2UJ5Ws shardul@sharchy"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG/hHV1C/aghxw/CdSKgpSWcPI0vKI9bV2bDZYfnJ7nT Generated By Termius"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJo9B32sfzU4LF4SATBenldO248t4BadFcUNG9y6T1Kx amp-dotfiles-deploy"
    ];
    linger = true;
    shell = pkgs.zsh;
  };

  programs.zsh.enable = true;
  programs.ssh.extraConfig = ''
    SendEnv LANG LC_*
  '';
  programs._1password.enable = true;
  programs._1password-gui = {
    enable = true;
    polkitPolicyOwners = [ "shardul" ];
  };
  programs.helium = {
    enable = true;
    flags = [
      "--ozone-platform=wayland"
      "--ozone-platform-hint=wayland"
      "--enable-features=TouchpadOverscrollHistoryNavigation,VerticalTabs"
      "--load-extension=/home/shardul/.config/helium/extensions/alt-click-new-tab"
    ];
    policies = {
      PasswordManagerEnabled = false;
      BrowserColorScheme = "device";
      ExtensionSettings = {
        "*".installation_mode = "allowed";
        "dbepggeogbaibhgnhhndojpepiihcmeb" = {
          installation_mode = "force_installed";
          update_url = "https://services.helium.imput.net/ext";
        };
        "aeblfdkhhhdcdjpifhhbdiojplfjncoa" = {
          installation_mode = "force_installed";
          update_url = "https://services.helium.imput.net/ext";
        };
      };
    };
  };
  environment.etc."1password/custom_allowed_browsers" = {
    text = "helium\n";
    mode = "0644";
  };
  environment.localBinInPath = true;

  services.openssh = {
    enable = true;
    settings = {
      KbdInteractiveAuthentication = false;
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };
  security.sudo.wheelNeedsPassword = false;
  services.tailscale = {
    enable = true;
    # The tagged deploy orb uses standard OpenSSH because Tailscale SSH does
    # not allow tagged sources to log in to an untagged personal device.
    extraSetFlags = [ "--ssh=false" ];
  };
  networking.networkmanager.enable = true;
  services.fstrim.enable = true;
  services.fwupd.enable = true;
  services.power-profiles-daemon.enable = true;
  zramSwap.enable = true;

  programs.hyprland = {
    enable = true;
    withUWSM = true;
    xwayland.enable = true;
  };
  programs.uwsm.enable = true;
  services.greetd = {
    enable = true;
    settings.default_session = {
      command = greeterSession;
      user = "greeter";
    };
  };
  environment.sessionVariables.NIXOS_OZONE_WL = "1";
  systemd.tmpfiles.rules = [
    "d /run/sharchy 0755 shardul users -"
    "f /run/sharchy/theme 0644 shardul users -"
  ];
  programs.dconf.enable = true;
  programs.nix-ld.enable = true;
  xdg.portal = {
    enable = true;
    extraPortals = with pkgs; [ xdg-desktop-portal-gtk xdg-desktop-portal-hyprland ];
    config.common.default = [ "hyprland" "gtk" ];
  };
  security.polkit = {
    enable = true;
    enablePkexecWrapper = true;
  };
  security.pam.services.sharchy-lock = { };
  security.pam.services.greetd.enableGnomeKeyring = true;
  systemd.services."getty@tty2".wantedBy = [ "getty.target" ];
  services.dbus.enable = true;
  services.gnome.gnome-keyring.enable = true;
  services.upower.enable = true;
  services.blueman.enable = true;
  services.xremap = {
    enable = true;
    serviceMode = "user";
    userName = "shardul";
    withHypr = true;
    config.keymap = [
      {
        name = "macOS editing";
        application.not = [ "com.mitchellh.ghostty" ];
        remap = {
          "ALT-C" = "CTRL-C";
          "ALT-V" = "CTRL-V";
          "ALT-X" = "CTRL-X";
          "ALT-A" = "CTRL-A";
          "ALT-Z" = "CTRL-Z";
          "ALT-BACKSPACE" = [ "SHIFT-HOME" "BACKSPACE" ];
          "ALT-LEFT" = "HOME";
          "ALT-RIGHT" = "END";
          "SUPER-BACKSPACE" = "CTRL-BACKSPACE";
          "SUPER-LEFT" = "CTRL-LEFT";
          "SUPER-RIGHT" = "CTRL-RIGHT";
          "SUPER-SHIFT-LEFT" = "CTRL-SHIFT-LEFT";
          "SUPER-SHIFT-RIGHT" = "CTRL-SHIFT-RIGHT";
        };
      }
      {
        name = "Helium tabs";
        application.only = [ "helium" ];
        remap = {
          "ALT-T" = "CTRL-T";
          "ALT-L" = "CTRL-L";
          "ALT-F" = "CTRL-F";
          "ALT-N" = "CTRL-N";
          "ALT-SHIFT-N" = "CTRL-SHIFT-N";
          "ALT-W" = "CTRL-W";
          "ALT-SHIFT-W" = "CTRL-SHIFT-W";
          "ALT-R" = "CTRL-R";
          "ALT-SHIFT-R" = "CTRL-SHIFT-R";
          "ALT-SHIFT-T" = "CTRL-SHIFT-T";
          "ALT-1" = "CTRL-1";
          "ALT-2" = "CTRL-2";
          "ALT-SHIFT-3" = "ALT-SHIFT-3";
          "ALT-SHIFT-4" = "ALT-SHIFT-4";
          "ALT-3" = "CTRL-3";
          "ALT-4" = "CTRL-4";
          "ALT-5" = "CTRL-5";
          "ALT-6" = "CTRL-6";
          "ALT-7" = "CTRL-7";
          "ALT-8" = "CTRL-8";
          "ALT-9" = "CTRL-9";
          "ALT-LEFTBRACE" = "ALT-LEFT";
          "ALT-RIGHTBRACE" = "ALT-RIGHT";
          "ALT-SHIFT-LEFTBRACE" = "CTRL-PAGEUP";
          "ALT-SHIFT-RIGHTBRACE" = "CTRL-PAGEDOWN";
        };
      }
    ];
  };
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  fonts.packages = with pkgs; [ jetbrains-mono nerd-fonts.jetbrains-mono ];
  environment.systemPackages = with pkgs; [
    adwaita-icon-theme apple-cursor brightnessctl blueman btrfs-progs
    cryptsetup curl discord fuzzel ghostty git grim glib jq libnotify mako
    networkmanagerapplet obsidian pavucontrol pciutils quickshell ripgrep slurp swaybg
    swayidle usbutils vicinae vim wget wl-clipboard wtype
  ];

  home-manager.users.shardul = { config, pkgs, ... }:
    let
      grok-bot = pkgs.callPackage ../packages/grok-bot.nix { };
      hermes-desktop = pkgs.callPackage ../packages/hermes-desktop.nix { inherit hermes; };
      lockShell = ../config/quickshell-lock.qml;
      lockConfig = pkgs.runCommand "sharchy-lock-config" { } ''
        mkdir -p "$out"
        cp ${lockShell} "$out/shell.qml"
        cp ${authQml} "$out/AlabasterAuth.qml"
      '';
      wallpaper = pkgs.writeShellScript "sharchy-wallpaper" ''
        mode="$(${pkgs.coreutils}/bin/cat /home/shardul/.local/state/sharchy-theme 2>/dev/null || true)"
        if [ "$mode" = dark ]; then color="#14120b"; else color="#e5e4df"; fi
        exec ${pkgs.swaybg}/bin/swaybg -c "$color"
      '';
      makoTheme = pkgs.writeShellScript "sharchy-mako-theme" ''
        mode="$(${pkgs.coreutils}/bin/cat /home/shardul/.local/state/sharchy-theme 2>/dev/null || true)"
        if [ "$mode" != dark ]; then mode=light; fi
        for _ in $(${pkgs.coreutils}/bin/seq 1 20); do
          if ${pkgs.mako}/bin/makoctl mode -s "$mode"; then exit 0; fi
          ${pkgs.coreutils}/bin/sleep 0.05
        done
        exit 0
      '';
      vicinaeTheme = pkgs.writeShellScript "sharchy-vicinae-theme" ''
        mode="$(${pkgs.coreutils}/bin/cat /home/shardul/.local/state/sharchy-theme 2>/dev/null || true)"
        if [ "$mode" != dark ]; then mode=light; fi
        for _ in $(${pkgs.coreutils}/bin/seq 1 20); do
          if ${pkgs.vicinae}/bin/vicinae ping >/dev/null 2>&1; then
            exec ${pkgs.vicinae}/bin/vicinae theme set "alabaster-$mode"
          fi
          ${pkgs.coreutils}/bin/sleep 0.05
        done
        exit 1
      '';
    in
    {
      home.homeDirectory = "/home/shardul";
      home.packages = with pkgs; [
        clang_22
        grok-bot
        hermes-desktop
      ];
      home.pointerCursor = {
        enable = true;
        package = pkgs.apple-cursor;
        name = "macOS";
        size = 24;
        gtk.enable = true;
        x11.enable = true;
      };

      home.file.".local/bin/sharchy-fuzzel".source = ../scripts/sharchy-fuzzel.sh;
      home.file.".local/bin/sharchy-helium".source = ../scripts/sharchy-helium.sh;
      home.file.".local/bin/sharchy-helium-defaults".source = ../scripts/sharchy-helium-defaults.sh;
      home.file.".local/bin/sharchy-screenshot".source = ../scripts/sharchy-screenshot.sh;
      home.file.".local/bin/sharchy-theme".source = ../scripts/sharchy-theme.sh;
      home.file.".local/bin/sharchy-keybindings".source = ../scripts/sharchy-keybindings.sh;
      home.file.".local/bin/sharchy-layout-toggle".source = ../scripts/sharchy-layout-toggle.sh;
      home.file.".local/bin/sharchy-rebuild".source = ../scripts/sharchy-rebuild.sh;

      systemd.user.services.amp-runner = {
        Unit = {
          Description = "Amp remote runner";
          After = [ "network-online.target" ];
          Wants = [ "network-online.target" ];
        };
        Service = {
          Environment = "HOME=/home/shardul";
          WorkingDirectory = "/home/shardul";
          ExecStart = "${pkgs.amp-cli}/bin/amp --no-tui --runner-id sharchy --remote-control-terminal";
          Restart = "always";
          RestartSec = 5;
        };
        Install.WantedBy = [ "default.target" ];
      };
      systemd.user.services.vicinae = {
        Unit = {
          Description = "Vicinae launcher";
          After = [ "graphical-session.target" ];
          PartOf = [ "graphical-session.target" ];
          Requires = [ "dbus.socket" ];
          X-Restart-Triggers = [
            "${config.xdg.dataFile."vicinae/themes/alabaster-light.toml".source}"
            "${config.xdg.dataFile."vicinae/themes/alabaster-dark.toml".source}"
          ];
        };
        Service = {
          ExecStart = "${pkgs.vicinae}/bin/vicinae server --replace";
          ExecStartPost = vicinaeTheme;
          KillMode = "process";
          Restart = "always";
          RestartSec = 60;
        };
        Install.WantedBy = [ "graphical-session.target" ];
      };
      systemd.user.services.sharchy-bar = {
        Unit = {
          Description = "Sharchy desktop shell";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
          X-Restart-Triggers = [ "${config.xdg.configFile."quickshell/sharchy/shell.qml".source}" ];
        };
        Service = {
          ExecStartPre = [
            "-${pkgs.systemd}/bin/systemctl --user stop hyprpolkitagent.service"
            "${pkgs.coreutils}/bin/mkdir -p /home/shardul/.local/state"
            "${pkgs.coreutils}/bin/touch /home/shardul/.local/state/sharchy-rebuild-status"
          ];
          ExecStart = "${pkgs.quickshell}/bin/quickshell -p /home/shardul/.config/quickshell/sharchy";
          Restart = "on-failure";
          RestartSec = 1;
          Environment = "QS_NO_RELOAD_POPUP=1";
        };
        Install.WantedBy = [ "graphical-session.target" ];
      };
      systemd.user.services.sharchy-wallpaper = {
        Unit = {
          Description = "Alabaster desktop wallpaper";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
        };
        Service = { ExecStart = wallpaper; Restart = "on-failure"; RestartSec = 1; };
        Install.WantedBy = [ "graphical-session.target" ];
      };
      systemd.user.services.sharchy-lock = {
        Unit = {
          Description = "Alabaster session lock";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
        };
        Service = {
          ExecStart = "${pkgs.quickshell}/bin/quickshell -p ${lockConfig}";
          Restart = "on-failure";
          RestartSec = 1;
        };
      };
      systemd.user.services.mako = {
        Unit = {
          Description = "Mako notification daemon";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
          X-Restart-Triggers = [ "${config.xdg.configFile."mako/config".source}" ];
        };
        Service = {
          ExecStart = "${pkgs.mako}/bin/mako";
          ExecStartPost = makoTheme;
          Restart = "on-failure";
        };
        Install.WantedBy = [ "graphical-session.target" ];
      };
      systemd.user.services.sharchy-helium-defaults = {
        Unit = { Description = "Enable Helium extension downloads"; Before = [ "graphical-session.target" ]; };
        Service = { Type = "oneshot"; ExecStart = "/home/shardul/.local/bin/sharchy-helium-defaults"; };
        Install.WantedBy = [ "graphical-session.target" ];
      };
      systemd.user.services.sharchy-theme-scheduled = {
        Unit.Description = "Apply the scheduled Sharchy theme";
        Service = { Type = "oneshot"; ExecStart = "/home/shardul/.local/bin/sharchy-theme scheduled"; };
      };
      systemd.user.timers.sharchy-theme-scheduled = {
        Unit.Description = "Switch themes at 07:00 and 19:00";
        Timer = { OnCalendar = "*-*-* 07,19:00:00"; Persistent = true; };
        Install.WantedBy = [ "timers.target" ];
      };

      # Mask terminal-only launchers; Fuzzel should contain GUI applications.
      xdg.dataFile."applications/vim.desktop".text = ''
        [Desktop Entry]
        Type=Application
        Name=Vim
        Hidden=true
      '';
      xdg.configFile."fuzzel/fuzzel.ini".source = ../config/fuzzel.ini;
      xdg.configFile."fuzzel/light.ini".source = ../config/fuzzel-light.ini;
      xdg.configFile."fuzzel/dark.ini".source = ../config/fuzzel-dark.ini;
      xdg.configFile."ghostty/config".source = ../config/ghostty-linux.conf;
      xdg.configFile."helium/extensions/alt-click-new-tab/background.js".source = ../config/browser-extension/background.js;
      xdg.configFile."helium/extensions/alt-click-new-tab/content.js".source = ../config/browser-extension/content.js;
      xdg.configFile."helium/extensions/alt-click-new-tab/manifest.json".source = ../config/browser-extension/manifest.json;
      xdg.configFile."hypr/hyprland.lua".source = ../config/hyprland.lua;
      xdg.configFile."mako/config".source = ../config/mako.conf;
      xdg.configFile."quickshell/sharchy/shell.qml".source = ../config/sharchy-shell.qml;
      xdg.dataFile."vicinae/themes/alabaster-light.toml".source = ../config/vicinae-light.toml;
      xdg.dataFile."vicinae/themes/alabaster-dark.toml".source = ../config/vicinae-dark.toml;
      xdg.dataFile."applications/chrome-bpgpkfmeagdpdcenbogglipmfkalmple-Default.desktop".text = ''
        [Desktop Entry]
        Version=1.0
        Type=Application
        Name=Amp
        Exec=/home/shardul/.local/bin/sharchy-helium --profile-directory=Default --app-id=bpgpkfmeagdpdcenbogglipmfkalmple
        Icon=chrome-bpgpkfmeagdpdcenbogglipmfkalmple-Default
        StartupWMClass=crx_bpgpkfmeagdpdcenbogglipmfkalmple
        Terminal=false
      '';
      xdg.desktopEntries.helium = {
        name = "Helium";
        genericName = "Web Browser";
        exec = "/home/shardul/.local/bin/sharchy-helium %U";
        icon = "helium";
        terminal = false;
        categories = [ "Network" "WebBrowser" ];
        mimeType = [ "text/html" "x-scheme-handler/http" "x-scheme-handler/https" ];
      };
    };

  system.stateVersion = "26.05";
}
