start-at-login = true
accordion-padding = 10
default-root-container-layout = 'tiles'
key-mapping.preset = 'qwerty'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

[mode.main.binding]
alt-h = 'focus --boundaries all-monitors-outer-frame left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus --boundaries all-monitors-outer-frame right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-space = 'move-workspace-to-monitor next --wrap-around'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-3 = 'workspace 3'
alt-0 = 'workspace Z'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-0 = 'move-node-to-workspace Z'

[[on-window-detected]]
if.app-name-regex-substring = 'Zed'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-name-regex-substring = 'Ghostty'
run = ['layout floating', 'move-node-to-workspace Z']

[[on-window-detected]]
if.app-name-regex-substring = 'Chrome'
run = ['move-node-to-workspace 3']
