mode = "dark"

accent = "#cd974b"
selection = "#3a382f"
muted = "#777777"

background = "#14120b"
dark_background = "#0f0d08"
darker_background = "#090805"
lighter_background = "#242218"

foreground = "#cecece"
dark_foreground = "#777777"
light_foreground = "#d8d8d8"
bright_foreground = "#ffffff"

red = "#d66a64"
yellow = "#c7a55f"
orange = "#cd974b"
green = "#8fb980"
cyan = "#6faeb3"
blue = "#739fc8"
magenta = "#b986b5"
brown = "#7a5a3a"

bright_red = "#e47e78"
bright_yellow = "#d5b773"
bright_green = "#a5ca98"
bright_cyan = "#88c0c4"
bright_blue = "#8bb2d5"
bright_magenta = "#c99bc5"
