[shell]
font_family = "JetBrainsMono Nerd Font"
settings_show_advanced = true
telemetry_enabled = false
polkit_agent = false
clipboard_enabled = true
clipboard_keep_from_closed_apps = false
clipboard_auto_paste = "auto"

[shell.animation]
enabled = false
speed = 1.0

[shell.panel]
transparency_mode = "solid"
borders = true
shadow = true
launcher_placement = "floating"
launcher_position = "center"
control_center_placement = "attached"
session_placement = "attached"

[shell.launcher]
categories = true
show_icons = true
show_app_origin_indicator = true
sort_by_usage = true
provider_prefix = "/"

[shell.screenshot]
save_to_file = true
copy_to_clipboard = true
freeze_screen = true
confirm_region = false
directory = "/home/shardul/Pictures/Screenshots"
filename_pattern = "screenshot_%Y%m%d_%H%M%S"

[wallpaper]
enabled = false

[theme]
mode = "dark"
source = "builtin"
builtin = "Noctalia"
pure_black_dark = false

[theme.templates]
enable_builtin_templates = true
builtin_ids = ["gtk3", "gtk4"]
enable_community_templates = false
community_ids = []

[notification]
enable_daemon = true
show_app_name = true
show_actions = true
position = "top_right"
background_opacity = 0.97

[lockscreen]
enabled = true
blurred_desktop = false

[system.monitor]
enabled = true

[bar.main]
position = "top"
thickness = 32
background_opacity = 1.0
radius = 0
margin_ends = 0
margin_edge = 0
padding = 8
widget_spacing = 3
shadow = false
reserve_space = true
capsule = false
start = ["launcher", "workspaces"]
center = ["clock"]
end = ["media", "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "theme_mode", "control-center", "session"]

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "wallpaper"

[[control_center.shortcuts]]
type = "session"
