--ozone-platform=wayland
--ozone-platform-hint=wayland
--password-store=basic
--enable-features=TouchpadOverscrollHistoryNavigation,VerticalTabs
--load-extension=/home/shardul/.config/chromium/extensions/alt-click-new-tab
