matches:
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":countby"
    replace: "summarize count() by"

  - trigger: ":nochanges"
    replace: "**CRITICAL**: Do not make any changes to any files yet. Simply output text that answers the prompt that I have provided."

  - trigger: ":runandplan"
    replace: "Run it again, and describe the output. If it is not successful, give me a plan of attack once again. {{nochanges}}"
    vars:
      - name: nochanges
        type: match
        params:
          trigger: ":nochanges"
