[tools]
go = "latest"
node = "latest"
pnpm = "latest"
ruby = "latest"
amp = "latest"
claude = "latest"
codex = "latest"
uv = "latest"
atuin = "latest"
bat = "latest"
direnv = "latest"
difftastic = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
hyperfine = "latest"
jj = "latest"
jjui = "latest"
jq = "latest"
neovim = "latest"
ripgrep = "latest"
zoxide = "latest"
tmux = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
